### ISSUE TITLE
 ERROR: 'it should return the callSid : everything's fine'

### ISSUE THREAD

**Issue by Keiserthegreat** [Oriyomi12/otp-bot#31]
When I run  npm test 25/26 tests past except for this one on Call.js

**Comment by Keiserthegreat** [comment]
Update: Figured how to fix it.

**Comment by RohanJose** [comment]
> Update: Figured how to fix it.

Could you please help?

**Comment by Keiserthegreat** [comment]
On line 122 in the Call.js file api/test/call.js, change the number to your twilio number

**Comment by Ishura911** [comment]
Please help me. When i run npm test I have more error. Must I paid my twilio account or verify please send me msg on telegram https://t.me/thorfinn95
